version: "3.8"

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "8000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src:/var/www/slim
    depends_on:
      - mysql
      - php

  php:
    build:
      context: dockerfiles
      dockerfile: php.Dockerfile
    volumes:
      - ./src:/var/www/slim

  mysql:
    image: mysql:8.0
    ports:
      - "3308:3306"
    env_file:
      - env/mysql.env
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8010:80"
    environment:
      - PMA_ARBITRARY=1

volumes:
  db_data:
